services:
  nginx:
    build: ".docker/nginx"
    container_name: laravel-sample-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: ".docker/app"
    container_name: laravel-sample-app
    working_dir: /app
    volumes:
      - ".:/app"
    ports:
      - "9000:9000"
    tty: true
    env_file:
      - .env
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: laravel-sample-mysql
    build: ".docker/mysql"
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
